site_name: xkoranate-CE
site_description: User guide for xkoranate-ce-python, the sports scorinator for NS Sports
site_url: https://lukeplatts.github.io/xkoranate-ce-python/
repo_url: https://github.com/lukeplatts/xkoranate-ce-python
repo_name: lukeplatts/xkoranate-ce-python
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - content.action.edit
    - content.code.copy

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Building an event: building-an-event.md
  - Table generator: table-generator.md
  - RP bonuses: rp-bonuses.md
  - Settings & file locations: settings.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lukeplatts/xkoranate-ce-python
